### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Jackie78De** [kboghdady/youTube_ads_4_pi-hole#1]
The script doesn't work on my Raspi3 running Pihole:

`pi@pihole3:~ $ sudo python /home/pi/youtube.sh
  File "/home/pi/youtube.sh", line 9
    piholeIPV4=`hostname -I |awk '{print $1}'`
                                            ^
SyntaxError: invalid syntax`

Anything except gawk that needs to be installed?

**Comment by kboghdady** [comment]
I will look into that Jackie78De  and get back to you as soon as I can

**Comment by kboghdady** [comment]
Hey Jackie, 
I am sorry.I had a wrong line in the documentation. 
You should run the code only with  sudo /home/pi/youtube.sh
My apology about that.
