### ISSUE TITLE
Pi-Hole Dashboard: "Domains on Blocklist" not updating?

### ISSUE THREAD

**Issue by burntwilly** [kboghdady/youTube_ads_4_pi-hole#102]
I believe I have everything configured properly, and while I have no idea if anything is actually working, my question is this: If I am using this with a pi-hole, is the "Domains on Blocklist" on the web dashboard supposed to increase after the youtube.sh script completes?

**Comment by kboghdady** [comment]
yes it should 
also if you run pihole -g you should see the list be update from the internet
