### ISSUE TITLE
Can adguardhome use this rule?

### ISSUE THREAD

**Issue by kittyzero520** [kboghdady/youTube_ads_4_pi-hole#109]
I use adguardhome, not PI hole. Is the rule universal?

**Comment by angelss197200** [comment]
just asking 
what it is the adguard.txt file?

**Comment by kboghdady** [comment]
I use to generate the adguard.txt where you can use it with adgaurd, but I can no longer add it to get it because it becomes so big. 
you can get the black.list and convert it with the adguard format
