### ISSUE TITLE
block youtube video itself

### ISSUE THREAD

**Issue by GuillaumeBeaudoin** [kboghdady/youTube_ads_4_pi-hole#11]

**Comment by kboghdady** [comment]
I will investigate this

**Comment by GuillaumeBeaudoin** [comment]
> I will investigate this

r2---sn-8qu-t0a6.googlevideo.com
r2---sn-8qu-t0ay.googlevideo.com
r4---sn-t0a7ln7d.googlevideo.com
r5---sn-8qu-t0a6.googlevideo.com


i add to manually add these to white list so my video could play, i had many more but i updated my block list and i lost few domain

**Comment by kboghdady** [comment]
I have fixed the issue by making the updates to the file, and getting the list from the GitHub file which will be updated every day or week.
