### ISSUE TITLE
black.txt hasnt been updated recently

### ISSUE THREAD

**Issue by herotm** [kboghdady/youTube_ads_4_pi-hole#111]
are we going to see more updates soon?

works decent so far

**Comment by yllekz** [comment]
Also curious about this. This list hasn't been successfully blocking ads on YouTube on the Apple TV, and it actually stops a few legit videos from loading as well.

**Comment by kboghdady** [comment]
I am sorry I was changing my home network and got the server that updates down. I will get it back online soon
