### ISSUE TITLE
Blocking YT Videos

### ISSUE THREAD

**Issue by AgentJeffy** [kboghdady/youTube_ads_4_pi-hole#112]
Good Afternoon,

I added 's.youtube.com' to the whitelist and added:
'https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/youtubelist.txt'
'https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/crowed_list.txt'
to the group-adlists however it's blocking all YT video playing. It will load the thumbnails fine, but will not actually play anything. Just gets stuck loading.

I don't know how to add a script to the PiHole to run the commands you suggested, but I don't think that's the issue as I was already running the online updater when importing the Adlists.

**Comment by kboghdady** [comment]
@AgentJeffy to remove all the list you need to ssh to the pihole system to execute these commands

**Comment by DaZel77** [comment]
Can you please write what you just said in code please. This has happened to me as well

**Comment by jasker5183** [comment]
I've been using this list with pfBlockerNG for quite some time. But up until around five days started having issues where video's would not load. Even have `s.youtube.com` in the whitelist but still nothing. Any idea what's going on here?

**Comment by kboghdady** [comment]
it is in the read me 
/usr/bin/sqlite3 /etc/pihole/gravity.db "delete from gravity where domain like '%googlevideo.com%' "
pihole -g
