### ISSUE TITLE
missing .com on lines

### ISSUE THREAD

**Issue by kartondoos** [kboghdady/youTube_ads_4_pi-hole#114]
## Hey kboghdady,
I was using your list and was curious what was in the block list and was a couple of errors in the list. 
Maybe they are intentional but if not here are the lines where I think the .com is missing on some of the domains.

Kind regards,
Kartondoos 

##
## line 4544-456
r1.sn-p5qs7nek.a1.googlevideo
r2.sn-p5qs7nek.a1.googlevideo
r3.sn-p5qs7nek.a1.googlevideo
r4.sn-p5qs7nek.a1.googlevideo
r5.sn-p5qs7nek.a1.googlevideo
r6.sn-p5qs7nek.a1.googlevideo
r7.sn-p5qs7nek.a1.googlevideo
r8.sn-p5qs7nek.a1.googlevideo
r9.sn-p5qs7nek.a1.googlevideo
r10.sn-p5qs7nek.a1.googlevideo
r11.sn-p5qs7nek.a1.googlevideo
r12.sn-p5qs7nek.a1.googlevideo
r13.sn-p5qs7nek.a1.googlevideo
r14.sn-p5qs7nek.a1.googlevideo
r15.sn-p5qs7nek.a1.googlevideo
r16.sn-p5qs7nek.a1.googlevideo
r17.sn-p5qs7nek.a1.googlevideo
r18.sn-p5qs7nek.a1.googlevideo
r19.sn-p5qs7nek.a1.googlevideo
r20.sn-p5qs7nek.a1.googlevideo

## line9325-9344
r1.sn-n4v7knls.a1.googlevideo
r2.sn-n4v7knls.a1.googlevideo
r3.sn-n4v7knls.a1.googlevideo
r4.sn-n4v7knls.a1.googlevideo
r5.sn-n4v7knls.a1.googlevideo
r6.sn-n4v7knls.a1.googlevideo
r7.sn-n4v7knls.a1.googlevideo
r8.sn-n4v7knls.a1.googlevideo
r9.sn-n4v7knls.a1.googlevideo
r10.sn-n4v7knls.a1.googlevideo
r11.sn-n4v7knls.a1.googlevideo
r12.sn-n4v7knls.a1.googlevideo
r13.sn-n4v7knls.a1.googlevideo
r14.sn-n4v7knls.a1.googlevideo
r15.sn-n4v7knls.a1.googlevideo
r16.sn-n4v7knls.a1.googlevideo
r17.sn-n4v7knls.a1.googlevideo
r18.sn-n4v7knls.a1.googlevideo
r19.sn-n4v7knls.a1.googlevideo
r20.sn-n4v7knls.a1.googlevideo

## line 11585 -  11624
r1.sn-uhvcpax0n5-nh4l.a1.googlevideo
r2.sn-uhvcpax0n5-nh4l.a1.googlevideo
r3.sn-uhvcpax0n5-nh4l.a1.googlevideo
r4.sn-uhvcpax0n5-nh4l.a1.googlevideo
r5.sn-uhvcpax0n5-nh4l.a1.googlevideo
r6.sn-uhvcpax0n5-nh4l.a1.googlevideo
r7.sn-uhvcpax0n5-nh4l.a1.googlevideo
r8.sn-uhvcpax0n5-nh4l.a1.googlevideo
r9.sn-uhvcpax0n5-nh4l.a1.googlevideo
r10.sn-uhvcpax0n5-nh4l.a1.googlevideo
r11.sn-uhvcpax0n5-nh4l.a1.googlevideo
r12.sn-uhvcpax0n5-nh4l.a1.googlevideo
r13.sn-uhvcpax0n5-nh4l.a1.googlevideo
r14.sn-uhvcpax0n5-nh4l.a1.googlevideo
r15.sn-uhvcpax0n5-nh4l.a1.googlevideo
r16.sn-uhvcpax0n5-nh4l.a1.googlevideo
r17.sn-uhvcpax0n5-nh4l.a1.googlevideo
r18.sn-uhvcpax0n5-nh4l.a1.googlevideo
r19.sn-uhvcpax0n5-nh4l.a1.googlevideo
r20.sn-uhvcpax0n5-nh4l.a1.googlevideo
r1.sn-o097znlk.a1.googlevideo
r2.sn-o097znlk.a1.googlevideo
r3.sn-o097znlk.a1.googlevideo
r4.sn-o097znlk.a1.googlevideo
r5.sn-o097znlk.a1.googlevideo
r6.sn-o097znlk.a1.googlevideo
r7.sn-o097znlk.a1.googlevideo
r8.sn-o097znlk.a1.googlevideo
r9.sn-o097znlk.a1.googlevideo
r10.sn-o097znlk.a1.googlevideo
r11.sn-o097znlk.a1.googlevideo
r12.sn-o097znlk.a1.googlevideo
r13.sn-o097znlk.a1.googlevideo
r14.sn-o097znlk.a1.googlevideo
r15.sn-o097znlk.a1.googlevideo
r16.sn-o097znlk.a1.googlevideo
r17.sn-o097znlk.a1.googlevideo
r18.sn-o097znlk.a1.googlevideo
r19.sn-o097znlk.a1.googlevideo
r20.sn-o097znlk.a1.googlevideo

## line 11765-11784
r1.sn-o097znlr.a1.googlevideo
r2.sn-o097znlr.a1.googlevideo
r3.sn-o097znlr.a1.googlevideo
r4.sn-o097znlr.a1.googlevideo
r5.sn-o097znlr.a1.googlevideo
r6.sn-o097znlr.a1.googlevideo
r7.sn-o097znlr.a1.googlevideo
r8.sn-o097znlr.a1.googlevideo
r9.sn-o097znlr.a1.googlevideo
r10.sn-o097znlr.a1.googlevideo
r11.sn-o097znlr.a1.googlevideo
r12.sn-o097znlr.a1.googlevideo
r13.sn-o097znlr.a1.googlevideo
r14.sn-o097znlr.a1.googlevideo
r15.sn-o097znlr.a1.googlevideo
r16.sn-o097znlr.a1.googlevideo
r17.sn-o097znlr.a1.googlevideo
r18.sn-o097znlr.a1.googlevideo
r19.sn-o097znlr.a1.googlevideo
r20.sn-o097znlr.a1.googlevideo

**Comment by kboghdady** [comment]
Thank you I will fix that
