### ISSUE TITLE
does not work on LG TV

### ISSUE THREAD

**Issue by Basti77** [kboghdady/youTube_ads_4_pi-hole#115]
hello and thank you for your work.
Your solution works on T which is opened from a browser, but not on my SmartTV (LG).
the TV got the correct IP settings DNS points to Pihole.
after I have activated this list remains after the start of a YT video ~10 black and then still comes advertising. 
Can it be that LG has built a fallback DNS?

**Comment by kboghdady** [comment]
some TVs start to have a proxy where they kind of avoid the current DNS that you have. 
Please check with your pihole if your TV is hitting the pihole and then go out ot not
