### ISSUE TITLE
Update youtube list

### ISSUE THREAD

**Issue by Titomrock21** [kboghdady/youTube_ads_4_pi-hole#116]
Is it possible to add this domains?

r13---sn-4gxx-25gee.googlevideo.com
r1---sn-4gxx-25gel.googlevideo.com
r5---sn-4gxx-25gel.googlevideo.com
r14---sn-4gxx-25gee.googlevideo.com
r5---sn-4gxx-25ge7.googlevideo.com
r4---sn-4gxx-25gel.googlevideo.com
r5---sn-4g5lznek.googlevideo.com
r5---sn-hpa7kn76.googlevideo.com
r6---sn-4gxx-25gee.googlevideo.com 
r5---sn-4gxx-25gee.googlevideo.com
r10---sn-4gxx-25gee.googlevideo.com
r15---sn-4gxx-25ge7.googlevideo.com
r5---sn-4gxx-25gy.googlevideo.com
r10---sn-4gxx-25ge7.googlevideo.com
r7---sn-4gxx-25ge7.googlevideo.com 
r14---sn-4gxx-25gy.googlevideo.com
r15---sn-4gxx-25gel.googlevideo.com
r13---sn-4gxx-25gy.googlevideo.com
r16---sn-4gxx-25gy.googlevideo.com
r3---sn-hpa7zns6.googlevideo.com
r9---sn-4gxx-25gee.googlevideo.com
r15---sn-4gxx-25gee.googlevideo.com
r8---sn-4gxx-25ge7.googlevideo.com
r3---sn-hpa7kn7d.googlevideo.com
r3---sn-4g5ednde.googlevideo.com
r11---sn-4gxx-25gel.googlevideo.com
r3---sn-4gxx-25gel.googlevideo.com
r2---sn-hpa7kn7z.googlevideo.com
r11---sn-4gxx-25gee.googlevideo.com
r8---sn-4gxx-25gel.googlevideo.com
r1---sn-4gxx-25gee.googlevideo.com

**Comment by kboghdady** [comment]
Sure
