### ISSUE TITLE
no black.list or blacklist file in the folder

### ISSUE THREAD

**Issue by mzy2240** [kboghdady/youTube_ads_4_pi-hole#12]
Howdy!

I am trying to use your script, however in the /etc/pihole/ folder I did not find black.list or blacklist file, the only file seems to be relevant to the ads list is called adlists.list. Will that affect the usage of the script? The pi-hole version is 4.3.2 (latest). Thank you in advance!

**Comment by kboghdady** [comment]
let me investigate and get back to you.

**Comment by kboghdady** [comment]
so the blacklist.txt is add once you add a domain name to the pihole; Otherwise, it won't be generated. 
so, I assume you didn't add any blacklist into your domain before. 
it should not affect the usage. 
Please feel free to ping me again if you have any questions.

**Comment by mzy2240** [comment]
Hi @kboghdady, I added a domain name to the pihole so now there are two blacklist files in the folder which is good. However, after one day's monitoring, the script does not work and nothing added to these blacklist files. Do you know the reason for that?

**Comment by kboghdady** [comment]
Are you using sudo ?

**Comment by kboghdady** [comment]
review the readme 
0 */4 * * * sudo /home/pi/youTube_ads_4_pi-hole/youtube.sh >/dev/null

**Comment by mzy2240** [comment]
Yes I am using sudo and exactly the same. One thing might be the reason is that I'm using Ubuntu on a SBC (aarch64, but not raspbian), so that might be the reason?

**Comment by mzy2240** [comment]
check the crontab log, did not see any errors nor any info that proves the script has been executed

**Comment by kboghdady** [comment]
I am not familiar with SBC 
but you can run the script manually and see if it work or not. 
you should be ended with black.list with the same lines as the one on the repo with 19120 lines

**Comment by mzy2240** [comment]
Yes it's working. So I guess I need to give the youtube.sh script a privilege by using chmod +x?

**Comment by kboghdady** [comment]
yes 
Good luck

**Comment by kboghdady** [comment]
Please let  me know if that was the issue so I can update the Readme
