### ISSUE TITLE
Cannot delete

### ISSUE THREAD

**Issue by SamboMambo** [kboghdady/youTube_ads_4_pi-hole#123]
I have tried everything. i even deleted the default adlist, somehow the blocklists keep re appearing.

crontab -e is empty

pinhole -b --nuke clears it for few seconds then they'd come back.

the folder I cloned from here is deleted

can you advise how to stop them from re appearing, they're killing the memory and it doesn't function properly

**Comment by kboghdady** [comment]
have you used it in the gravity list? 
Also, you need to run this command to remove it from your database 
/usr/bin/sqlite3 /etc/pihole/gravity.db "delete from domainlist where domain like '%googlevideo.com%' "

**Comment by SamboMambo** [comment]
Yes, I have tried, I read the description. The issue is thousands of lines are being pushed to the blocklist directly which overloads the memory. It would be easier to push it to a list and have this list gets updated. 

Anyway I uninstalled it and did a clean install, that was the only command's getting accepted. 

I was getting database is locked in almost everything.

**Comment by kboghdady** [comment]
you can fork the script into your own repo
and update it to your repo,then use the txt file into your gravity list.
