### ISSUE TITLE
The script is not working on centos/fedora based systems.

### ISSUE THREAD

**Issue by larieu** [kboghdady/youTube_ads_4_pi-hole#129]
It starts with this error

/opt/youTube_ads_4_pi-hole/youtube.sh: line 32: dpkg: command not found
sudo: apt-get: command not found

then is going .... crazy

**Comment by kboghdady** [comment]
you might have the solution here 
https://askubuntu.com/questions/491374/terminal-sudo-apt-get-command-not-found
