### ISSUE TITLE
Watch history is blocked

### ISSUE THREAD

**Issue by mzy2240** [kboghdady/youTube_ads_4_pi-hole#13]
@kboghdady The tracking watch history function seems to be blocked, verified using the Android Youtube App.

**Comment by kboghdady** [comment]
so could you please explain more. 
Also, if you run on the pihole this command ```pihole -t```
which will show a live feed of what is blocked or allowed via the pihole

**Comment by HellIsCool** [comment]
the url we are blocking for the add it seem that in that url one is for history recording,

**Comment by kboghdady** [comment]
> the url we are blocking for the add it seem that in that url one is for history recording,

@HellIsCool not sure what you mean

**Comment by HellIsCool** [comment]
s.youtube.com this link recorders the history. Please check

**Comment by kboghdady** [comment]
I checked, and I am not blocking that DNS.
Maybe you need to clear your black.list and have a fresh one

**Comment by kboghdady** [comment]
I am sorry I will close the issue as I didn't get any other feedback
