### ISSUE TITLE
How to incorporate this list in gravity in pie hole

### ISSUE THREAD

**Issue by HellIsCool** [kboghdady/youTube_ads_4_pi-hole#15]
we have this list in local raspberry pi but when i am adding /home/pi/youTube_ads_4_pi-hole/black.list it is showing following error.

[i] Target: local (black.list)
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

**Comment by kboghdady** [comment]
the black.list is not formatted for the gravity list. I am working on it and should be ready in the near future

**Comment by scyto** [comment]
@kboghdady i had a list that was working and downloaded just fine - i was using the github raw link, but it seemed to have stopped working recently.  I am confused if the github raw link can indeed be added to the block list list of lists?  It worked for weeks?!
