### ISSUE TITLE
youTube_ads_4_pi-hole breaks youtube

### ISSUE THREAD

**Issue by tonyp7** [kboghdady/youTube_ads_4_pi-hole#17]
Hi,

Thanks for this script. I tried it for a while but unfortunately it looks like it ended breaking YT completely. Videos would simply not load anymore. I ended up removing the script but it seems like the script bans too many domains, or at least some domains that deliver actual content.

Sorry not really any more details to add!

**Comment by kboghdady** [comment]
- Please wipe your blacklist by ``` sudo rm /etc/pihole/black* ``` or use the command ```sudo pihole -f ```
- because my previous development caused to block the youtube video itself
- The new script has been working great for me for the last couple days

**Comment by tonyp7** [comment]
Thanks I close this and will try the new version!

**Comment by kboghdady** [comment]
Could you please let me know how it goes

**Comment by tonyp7** [comment]
hey I figured I should update you: I still get a lot of ads but at least Youtube is no longer broken
