### ISSUE TITLE
Ur list is blocking youtube video's aswell.

### ISSUE THREAD

**Issue by JesperKuipers** [kboghdady/youTube_ads_4_pi-hole#18]
Ur list is blocking yt videos.

**Comment by kboghdady** [comment]
- Please wipe your blacklist by ``` sudo rm /etc/pihole/black* ``` or use the command ```sudo pihole -f ```
- because my previous development caused to block the youtube video itself
- The new script has been working great for me for the last couple days

**Comment by kboghdady** [comment]
you can also use ```pihole -t``` command to check which DNS is blocked
