### ISSUE TITLE
Not working anymore!

### ISSUE THREAD

**Issue by Profesyor** [kboghdady/youTube_ads_4_pi-hole#21]
Getting anoying, youtube black screens, videos not loading you need to go back or refresh ads still going tru! If the issue cannot be roleved please provide an easy way to uninstall/remove!

**Comment by kboghdady** [comment]
if you would like to uninstall : 
1- remove the cron job 
2- Please wipe your blacklist by sudo rm /etc/pihole/black*

I will look into the issue, but it is holiday time and I am quite busy. it would be helpful if you run ```pihole -t``` and let me know which DNS is showing while you have the black screen.

**Comment by frunkAF** [comment]
Happy Holidays!

I ran a pihole -t while trying to load up a youtube video and got this...

`19:00:38 dnsmasq[788]: query[A] r5---sn-a5meknzs.googlevideo.com from 10.255.255.1
19:00:38 dnsmasq[788]: /etc/pihole/gravity.list r5---sn-a5meknzs.googlevideo.com is 0.0.0.0
19:00:40 dnsmasq[788]: query[A] r6---sn-a5mlrnel.googlevideo.com from 10.255.255.1
19:00:40 dnsmasq[788]: /etc/pihole/gravity.list r6---sn-a5mlrnel.googlevideo.com is 0.0.0.0
19:00:42 dnsmasq[788]: query[A] r5---sn-a5meknzs.googlevideo.com from 10.255.255.1
19:00:42 dnsmasq[788]: /etc/pihole/gravity.list r5---sn-a5meknzs.googlevideo.com is 0.0.0.0
19:00:42 dnsmasq[788]: query[A] r6---sn-a5mlrnel.googlevideo.com from 10.255.255.1
19:00:42 dnsmasq[788]: /etc/pihole/gravity.list r6---sn-a5mlrnel.googlevideo.com is 0.0.0.0
19:00:44 dnsmasq[788]: query[A] r5---sn-a5meknzs.googlevideo.com from 10.255.255.1
19:00:44 dnsmasq[788]: /etc/pihole/gravity.list r5---sn-a5meknzs.googlevideo.com is 0.0.0.0
19:00:47 dnsmasq[788]: query[A] r6---sn-a5mlrnel.googlevideo.com from 10.255.255.1
19:00:47 dnsmasq[788]: /etc/pihole/gravity.list r6---sn-a5mlrnel.googlevideo.com is 0.0.0.0
19:00:52 dnsmasq[788]: query[A] r5---sn-a5meknzs.googlevideo.com from 10.255.255.1
19:00:52 dnsmasq[788]: /etc/pihole/gravity.list r5---sn-a5meknzs.googlevideo.com is 0.0.0.0
19:00:52 dnsmasq[788]: query[A] r6---sn-a5mlrnel.googlevideo.com from 10.255.255.1
19:00:52 dnsmasq[788]: /etc/pihole/gravity.list r6---sn-a5mlrnel.googlevideo.com is 0.0.0.0
19:00:56 dnsmasq[788]: query[A] r5---sn-a5meknzs.googlevideo.com from 10.255.255.1
19:00:56 dnsmasq[788]: /etc/pihole/gravity.list r5---sn-a5meknzs.googlevideo.com is 0.0.0.0
19:01:04 dnsmasq[788]: query[A] r6---sn-a5mlrnel.googlevideo.com from 10.255.255.1
19:01:04 dnsmasq[788]: /etc/pihole/gravity.list r6---sn-a5mlrnel.googlevideo.com is 0.0.0.0
19:01:09 dnsmasq[788]: query[A] r5---sn-a5meknzs.googlevideo.com from 10.255.255.1
19:01:09 dnsmasq[788]: /etc/pihole/gravity.list r5---sn-a5meknzs.googlevideo.com is 0.0.0.0
`

It looks like refreshing it a couple of times did eventually play the video (and an ad).

**Comment by Profesyor** [comment]
> Happy Holidays!
> I ran a pihole -t while trying to load up a youtube video and got this...
> 19:00:38 dnsmasq[788]: query[A] r5---sn-a5meknzs.googlevideo.com from 10.255.255.1 19:00:38 dnsmasq[788]: /etc/pihole/gravity.list r5---sn-a5meknzs.googlevideo.com is 0.0.0.0 19:00:40 dnsmasq[788]: query[A] r6---sn-a5mlrnel.googlevideo.com from 10.255.255.1 19:00:40 dnsmasq[788]: /etc/pihole/gravity.list r6---sn-a5mlrnel.googlevideo.com is 0.0.0.0 19:00:42 dnsmasq[788]: query[A] r5---sn-a5meknzs.googlevideo.com from 10.255.255.1 19:00:42 dnsmasq[788]: /etc/pihole/gravity.list r5---sn-a5meknzs.googlevideo.com is 0.0.0.0 19:00:42 dnsmasq[788]: query[A] r6---sn-a5mlrnel.googlevideo.com from 10.255.255.1 19:00:42 dnsmasq[788]: /etc/pihole/gravity.list r6---sn-a5mlrnel.googlevideo.com is 0.0.0.0 19:00:44 dnsmasq[788]: query[A] r5---sn-a5meknzs.googlevideo.com from 10.255.255.1 19:00:44 dnsmasq[788]: /etc/pihole/gravity.list r5---sn-a5meknzs.googlevideo.com is 0.0.0.0 19:00:47 dnsmasq[788]: query[A] r6---sn-a5mlrnel.googlevideo.com from 10.255.255.1 19:00:47 dnsmasq[788]: /etc/pihole/gravity.list r6---sn-a5mlrnel.googlevideo.com is 0.0.0.0 19:00:52 dnsmasq[788]: query[A] r5---sn-a5meknzs.googlevideo.com from 10.255.255.1 19:00:52 dnsmasq[788]: /etc/pihole/gravity.list r5---sn-a5meknzs.googlevideo.com is 0.0.0.0 19:00:52 dnsmasq[788]: query[A] r6---sn-a5mlrnel.googlevideo.com from 10.255.255.1 19:00:52 dnsmasq[788]: /etc/pihole/gravity.list r6---sn-a5mlrnel.googlevideo.com is 0.0.0.0 19:00:56 dnsmasq[788]: query[A] r5---sn-a5meknzs.googlevideo.com from 10.255.255.1 19:00:56 dnsmasq[788]: /etc/pihole/gravity.list r5---sn-a5meknzs.googlevideo.com is 0.0.0.0 19:01:04 dnsmasq[788]: query[A] r6---sn-a5mlrnel.googlevideo.com from 10.255.255.1 19:01:04 dnsmasq[788]: /etc/pihole/gravity.list r6---sn-a5mlrnel.googlevideo.com is 0.0.0.0 19:01:09 dnsmasq[788]: query[A] r5---sn-a5meknzs.googlevideo.com from 10.255.255.1 19:01:09 dnsmasq[788]: /etc/pihole/gravity.list r5---sn-a5meknzs.googlevideo.com is 0.0.0.0 
> It looks like refreshing it a couple of times did eventually play the video (and an ad).

My problem described exactly, thanks.

**Comment by Profesyor** [comment]
Removed, is now even worse that the previous update. YouTube is too big for this, thanks anyway.

**Comment by tutyamxx** [comment]
Don't have to be rude ^. At least someone is doing something. Stop using it and move on with your life

**Comment by kboghdady** [comment]
I don’t appreciate the way you are talking or the way you asking for help.
I am glad that you removed it.
At the end of the day I invest the time I could to help people.
