### ISSUE TITLE
Transform list to valid blocklist

### ISSUE THREAD

**Issue by msberends** [kboghdady/youTube_ads_4_pi-hole#23]
If you have `black.list` transform to a valid (Pi-hole) blacklist like https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts, users would only need to add it under `their-pi-hole-ip/settings.php?tab=blocklists`.

It is very cumbersome to have users set a cronjob and add EVERYTHING you have to their own 'personal' Blacklist menu. 

If you transform the file yourself before you push a commit, users only have to add https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/black.list to the Settings menu, press <kbd>Save and Update</kbd> and BAM, Pi-hole does the rest (including the auto-update from your GitHub repo):

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/31037261/71478332-52eaad80-27ef-11ea-8277-b4adba7e29b5.png">

**Comment by msberends** [comment]
Example based on your file (with #22 fixed): https://gist.github.com/msberends/992ad46b173b9c0f1bc3add21fcebed2

And raw to use in the menu I mentioned: https://gist.githubusercontent.com/msberends/992ad46b173b9c0f1bc3add21fcebed2/raw/a7312e94571e6cf819b0d581a6ff21f0aaf620f1/YouTube-ads-block.txt

**Comment by kboghdady** [comment]
I do both options in the repo. 
here is the valid gravity list if you would like to add it 
https://github.com/kboghdady/youTube_ads_4_pi-hole/blob/master/youtubelist.txt
