### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by nguye205** [kboghdady/youTube_ads_4_pi-hole#24]
Video doesn't play when  **r5---sn-vgqsknll.googlevideo.com** is blocked

**Comment by gitcloneguy** [comment]
than take it out @nguye205

**Comment by Profesyor** [comment]
Where is #21 

RUDE! Can't take criticism, sends rude anonymous replies and deletes comment and even his rude replies. REPORTED!
1/22/2020 12:44 AM Kiro: I don’t appreciate the way you are talking or the way you asking for help.
I am glad that you removed it.
At the end of the day I invest the time I could to help people.

1/21/2020 10:53 PM Alexandru Maxim: Don't have to be rude ^. At least someone is doing something. Stop using it and move on with your life.

Likes to end his rude replies with "move on with your life"

Delete this one and move on with you life.

**Comment by Profesyor** [comment]
Issue #21 NOW CLOSED AND REMOVED! Was it ever fixed? Cancel culture much?

Ok lets talk like real men here.

You are A coward! Yesterday you sent me a private message telling me to "move on with my life" a message I couldn't find on the issue #21, so it's you. Same thing you did to someone who pointed out the line that caused the black screens, (I wish I could still see it now). You told him "add it to your whitelist and move on with your life" your patented liberal punchline. And then you removed his comment and your rude answer at the same time! What is this, your CRAP don't work "anymore" and people can't say or ask anything? Anyhow here it goes...

1/21/2020 10:53 PM Alexandru Maxim:
 Don't have to be rude ^. At least someone is doing something. Stop using it and move on with your life.

But you couldn't live with only that! The world needed to see your pink-blue haired, black nail polish rage! Or not. So you replied back on the ISSUE after about 2 hours.

1/22/2020 12:44 AM Kiro:
 I don’t appreciate the way you are talking or the way you asking for help. I am glad that you removed it. At the end of the day I invest the time I could to help people.

And quickly closed the issue 12:44 AM!

This used to work, and I loved it. It used to like pause the vid for a sec and continue, AD OWNED! But the ad's started slowly creeping in again. First 2 a day then ad's everyday. A new issue was started: Not working properly. Your most recent replies were: "I will check it this weekend and get back to you" and "I will be looking into that"
 Don't know what you did or not. BUT, your piece coding became annoying, and is now USELESS. Cause YouTubers are now recording their ad's in the videos.

Now, did I attack you? Did I tell you that I don't appreciate your work? I told you, I removed it cause it was getting ULTRA annoying with the YouTube black screens. And to keep refreshing the YouTube page will mess up your recommendations. And told you YouTube is bigger than this, and thanked you! I enjoyed it while it worked, for a week. You are one pink haired person, YouTube has thousands of pink haired dudes working the ad's department. Some might even be your friends, it's how you got this to work in the first place.
 Don't be a coward fool. You have the time to sent me stupid replies, and don't have the time to come forward and say:
 Friends YouTube has sadly updated their algorithms, in the mean time please disable # the cron job in order for videos to continue without refreshing. I'm working hard to solve this issue. Will update once it's ready, thanks.
 And quietly move on with YOUR life, cause you didn't have a solution. But noooo, you had to come for me and, quickly cancel me afterwards.

No wonder you're from California. You can rage quit anytime you like now, and move on with your life.

**Comment by Profesyor** [comment]
Issue #21 NOW CLOSED AND REMOVED! Was it ever fixed? Cancel culture much?

Ok lets talk like real men here.

You are A coward! Yesterday you sent me a private message telling me to "move on with my life" a message I couldn't find on the issue #21, so it's you. Same thing you did to someone who pointed out the line that caused the black screens, (I wish I could still see it now). You told him "add it to your whitelist and move on with your life" your patented liberal punchline. And then you removed his comment and your rude answer at the same time! What is this, your CRAP don't work "anymore" and people can't say or ask anything? Anyhow here it goes...

1/21/2020 10:53 PM Alexandru Maxim:
 Don't have to be rude ^. At least someone is doing something. Stop using it and move on with your life.

But you couldn't live with only that! The world needed to see your pink-blue haired, black nail polish rage! Or not. So you replied back on the ISSUE after about 2 hours.

1/22/2020 12:44 AM Kiro:
 I don’t appreciate the way you are talking or the way you asking for help. I am glad that you removed it. At the end of the day I invest the time I could to help people.

And quickly closed the issue 12:44 AM!

This used to work, and I loved it. It used to like pause the vid for a sec and continue, AD OWNED! But the ad's started slowly creeping in again. First 2 a day then ad's everyday. A new issue was started: Not working properly. Your most recent replies were: "I will check it this weekend and get back to you" and "I will be looking into that"
 Don't know what you did or not. BUT, your piece coding became annoying, and is now USELESS. Cause YouTubers are now recording their ad's in the videos.

Now, did I attack you? Did I tell you that I don't appreciate your work? I told you, I removed it cause it was getting ULTRA annoying with the YouTube black screens. And to keep refreshing the YouTube page will mess up your recommendations. And told you YouTube is bigger than this, and thanked you! I enjoyed it while it worked, for a week. You are one pink haired person, YouTube has thousands of pink haired dudes working the ad's department. Some might even be your friends, it's how you got this to work in the first place.
 Don't be a coward fool. You have the time to sent me stupid replies, and don't have the time to come forward and say:
 Friends YouTube has sadly updated their algorithms, in the mean time please disable # the cron job in order for videos to continue without refreshing. I'm working hard to solve this issue. Will update once it's ready, thanks.
 And quietly move on with YOUR life, cause you didn't have a solution. But noooo, you had to come for me and, quickly cancel me afterwards.

No wonder you're from California. You can rage quit anytime you like now, and move on with your life.

**Comment by Profesyor** [comment]
Issue #21 NOW CLOSED AND REMOVED! Was it ever fixed? Cancel culture much?

Ok lets talk like real men here.

You are A coward! Yesterday you sent me a private message telling me to "move on with my life" a message I couldn't find on the issue #21, so it's you. Same thing you did to someone who pointed out the line that caused the black screens, (I wish I could still see it now). You told him "add it to your whitelist and move on with your life" your patented liberal punchline. And then you removed his comment and your rude answer at the same time! What is this, your CRAP don't work "anymore" and people can't say or ask anything? Anyhow here it goes...

1/21/2020 10:53 PM Alexandru Maxim:
 Don't have to be rude ^. At least someone is doing something. Stop using it and move on with your life.

But you couldn't live with only that! The world needed to see your pink-blue haired, black nail polish rage! Or not. So you replied back on the ISSUE after about 2 hours.

1/22/2020 12:44 AM Kiro:
 I don’t appreciate the way you are talking or the way you asking for help. I am glad that you removed it. At the end of the day I invest the time I could to help people.

And quickly closed the issue 12:44 AM!

This used to work, and I loved it. It used to like pause the vid for a sec and continue, AD OWNED! But the ad's started slowly creeping in again. First 2 a day then ad's everyday. A new issue was started: Not working properly. Your most recent replies were: "I will check it this weekend and get back to you" and "I will be looking into that"
 Don't know what you did or not. BUT, your piece coding became annoying, and is now USELESS. Cause YouTubers are now recording their ad's in the videos.

Now, did I attack you? Did I tell you that I don't appreciate your work? I told you, I removed it cause it was getting ULTRA annoying with the YouTube black screens. And to keep refreshing the YouTube page will mess up your recommendations. And told you YouTube is bigger than this, and thanked you! I enjoyed it while it worked, for a week. You are one pink haired person, YouTube has thousands of pink haired dudes working the ad's department. Some might even be your friends, it's how you got this to work in the first place.
 Don't be a coward fool. You have the time to sent me stupid replies, and don't have the time to come forward and say:
 Friends YouTube has sadly updated their algorithms, in the mean time please disable # the cron job in order for videos to continue without refreshing. I'm working hard to solve this issue. Will update once it's ready, thanks.
 And quietly move on with YOUR life, cause you didn't have a solution. But noooo, you had to come for me and, quickly cancel me afterwards.

No wonder you're from California. You can rage quit anytime you like now, and move on with your life.

**Comment by Profesyor** [comment]
Keep deleting.

**Comment by kboghdady** [comment]
Thank you. 
I will fix that
