### ISSUE TITLE
Random local IP Addresses to black list?

### ISSUE THREAD

**Issue by tutyamxx** [kboghdady/youTube_ads_4_pi-hole#3]
So, I see some random ip addresses such as 8.8.8 or random local ip's from my devices added to blacklist? also it adds a ```<CNAME>``` as well. Fix please?

**Comment by kboghdady** [comment]
Sure I will work on that

**Comment by zwit5** [comment]
Having the same issue. Including DNS IPs as well.

**Comment by kboghdady** [comment]
I am sorry I was busy the last couple weeks. I will be working on it this weekend. 
Thank y'all for your feedback

**Comment by kboghdady** [comment]
Fixed the issues. Thank y'all for your feedback. I really appreciate it
