### ISSUE TITLE
lots of sites missing 

### ISSUE THREAD

**Issue by qnarkill** [kboghdady/youTube_ads_4_pi-hole#33]
https://www.rtsak.com/cidr/2001:998::-30

IP | Type | Hostname
-- | -- | --
2001:998:12:59::c | A | r1.sn-xap5-ixaz.googlevideo.com
2001:998:12:59::c | A | r1---sn-xap5-ixaz.googlevideo.com
2001:998:12:59::d | A | r2---sn-xap5-ixaz.googlevideo.com
2001:998:12:59::e | A | r3.sn-xap5-ixaz.googlevideo.com
2001:998:12:59::e | A | r3---sn-xap5-ixaz.googlevideo.com
2001:998:12:59::f | A | r4.sn-xap5-ixaz.googlevideo.com
2001:998:12:59::f | A | r4---sn-xap5-ixaz.googlevideo.com
2001:998:12:59::10 | A | r5---sn-xap5-ixaz.googlevideo.com
2001:998:12:59::11 | A | r6---sn-xap5-ixaz.googlevideo.com
2001:998:12:59::12 | A | r7---sn-xap5-ixaz.googlevideo.com
2001:998:12:59::13 | A | r8.sn-xap5-ixaz.googlevideo.com
2001:998:12:59::13 | A | r8---sn-xap5-ixaz.googlevideo.com
2001:998:12:5a::c | A | r1---sn-xap5-ixas.googlevideo.com
2001:998:12:5a::d | A | r2---sn-xap5-ixas.googlevideo.com
2001:998:12:5a::d | A | r2.sn-xap5-ixas.googlevideo.com
2001:998:12:5a::e | A | r3---sn-xap5-ixas.googlevideo.com
2001:998:12:5a::e | A | r3.sn-xap5-ixas.googlevideo.com
2001:998:12:5a::f | A | r4.sn-xap5-ixas.googlevideo.com
2001:998:12:5a::f | A | r4.sn-xap5-ixas.c.pack.google.com
2001:998:12:5a::f | A | r4---sn-xap5-ixas.googlevideo.com
2001:998:12:5a::10 | A | r5.sn-xap5-ixas.googlevideo.com
2001:998:12:5a::10 | A | r5---sn-xap5-ixas.googlevideo.com
2001:998:12:5a::11 | A | r6---sn-xap5-ixas.googlevideo.com
2001:998:12:5a::11 | A | r6.sn-xap5-ixas.googlevideo.com
2001:998:12:5a::12 | A | r7---sn-xap5-ixas.googlevideo.com
2001:998:12:5a::13 | A | r8.sn-xap5-ixas.googlevideo.com
2001:998:12:5a::13 | A | r8---sn-xap5-ixas.googlevideo.com
2001:998:12:5b::c | A | r1---sn-xap5-ixal.googlevideo.com
2001:998:12:5b::c | A | r1.sn-xap5-ixal.googlevideo.com
2001:998:12:5b::d | A | r2.sn-xap5-ixal.googlevideo.com
2001:998:12:5b::e | A | r3---sn-xap5-ixal.googlevideo.com
2001:998:12:5b::e | A | r3.sn-xap5-ixal.googlevideo.com
2001:998:12:5b::f | A | r4---sn-xap5-ixal.googlevideo.com
2001:998:12:5b::f | A | r4.sn-xap5-ixal.googlevideo.com
2001:998:12:5b::10 | A | r5---sn-xap5-ixal.googlevideo.com
2001:998:12:5b::10 | A | r5.sn-xap5-ixal.googlevideo.com
2001:998:12:5b::11 | A | r6.sn-xap5-ixal.googlevideo.com
2001:998:12:5b::11 | A | r6---sn-xap5-ixal.googlevideo.com
2001:998:12:5b::12 | A | r7---sn-xap5-ixal.googlevideo.com
2001:998:12:5b::12 | A | r7.sn-xap5-ixal.googlevideo.com
2001:998:12:5b::13 | A | r8.sn-xap5-ixal.googlevideo.com
2001:998:12:5b::13 | A | r8---sn-xap5-ixal.googlevideo.com
2001:998:12:9a::c | A | r1.sn-xap5-ixa6.googlevideo.com
2001:998:12:9a::d | A | r2.sn-xap5-ixa6.googlevideo.com
2001:998:12:9a::e | A | r3.sn-xap5-ixa6.googlevideo.com
2001:998:12:9a::10 | A | r5.sn-xap5-ixa6.googlevideo.com
2001:998:12:9a::11 | A | r6.sn-xap5-ixa6.googlevideo.com
2001:998:12:9a::12 | A | r7.sn-xap5-ixa6.googlevideo.com
2001:998:12:9a::13 | A | r8.sn-xap5-ixa6.googlevideo.com

f.e.

**Comment by kboghdady** [comment]
so thee needs to be added to the block list?

**Comment by idoo** [comment]
@kboghdady looks like an answer is yes

**Comment by kboghdady** [comment]
done
