### ISSUE TITLE
Plans to update script for use in PiHole v5 (currently in beta)

### ISSUE THREAD

**Issue by fideld84** [kboghdady/youTube_ads_4_pi-hole#34]
Per this article https://pi-hole.net/2020/01/19/announcing-a-beta-test-of-pi-hole-5-0/#page-content
Moving forward, Pihole is moving to using a database (named - gravity.db) to store whitelist, blacklist, and gravity lists. This mean current scrips will have to be migrated to interacting with the database.  Any plans on doing making this happen, I'm currently on the PiHole Beta and unfortunately can't use your script.

**Comment by kboghdady** [comment]
Thank you very much @fideld84 for the update. 
I will definitely look into that

**Comment by kboghdady** [comment]
Would you be able to send me the "gravity.db" file.

**Comment by fideld84** [comment]
[gravity.zip](https://github.com/kboghdady/youTube_ads_4_pi-hole/files/4189144/gravity.zip)

**Comment by kboghdady** [comment]
Thank you very much @fideld84

**Comment by fideld84** [comment]
@kboghdady hope all is well, was wondering if you’ve had any progress/success with the Piholev5 script?

**Comment by drupol** [comment]
Why would you need that ? You just have to copy paste the URL in the UI and every week Pi Hole will update it automatically. There is no need to ship a script to update it!

**Comment by kboghdady** [comment]
I agree with @drupol 
just add the url to the new pihole.
