### ISSUE TITLE
is there a chance there will be a version for adguard home?

### ISSUE THREAD

**Issue by nik19okay** [kboghdady/youTube_ads_4_pi-hole#35]
I tried it in adguard home, found it not working by different format of the list, great work still, bravo.

**Comment by kboghdady** [comment]
if you can send me the format of the adgaurd I might be able to replicate it.

**Comment by nik19okay** [comment]
im not a pro but it seems insert "||" before every raw  and a "^" after every raw will do the job. the following are the official examples:
1. ||example.org^ – block access to the example.org domain and all its subdomains
2. @@||example.org^ – unblock access to the example.org domain and all its subdomains
3. 127.0.0.1 example.org – AdGuard Home will now return 127.0.0.1 address for the example.org    domain (but not its subdomains).
4. ! Here goes a comment – just a comment
5. # Also a comment – just a comment
6. /REGEX/ – block access to the domains matching the specified regular expression

**Comment by kboghdady** [comment]
I just made the adguard list for you

**Comment by nik19okay** [comment]
I'm grateful!
