### ISSUE TITLE
Differences between black.list and gravity.list

### ISSUE THREAD

**Issue by xziBBerx** [kboghdady/youTube_ads_4_pi-hole#37]
How does the shell script work? Because I can't find a path to gravity.list in youtube.sh. I use PiHole in Docker.

**Comment by xziBBerx** [comment]
And how i see you grab the black.list from you repository to variable blackListFile and blacklist.
where is there the differences? And how the script fill the gravity.list?

**Comment by kboghdady** [comment]
I just updated the file name on the documentation 
you can add this file https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/black.list
to your  Gravity list
