### ISSUE TITLE
Working Blocklist entry

### ISSUE THREAD

**Issue by frunkAF** [kboghdady/youTube_ads_4_pi-hole#39]
Hello!

Just a suggestion,

using the script to add the blacklist to '/etc/pihole' causes the gui to chug. My preferred method is to add a url to the blocklist.

Adding the url in your instructions...

https://github.com/kboghdady/youTube_ads_4_pi-hole/blob/master/youtubelist.txt

Doesn't get me the list.

However, adding the url you curl in your script...

https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/black.list

Successfully pulls the list and updates gravity!

**Comment by kboghdady** [comment]
Thank you @frunkAF I just updated the documentation
