### ISSUE TITLE
after longer usage of script youtube stops to open videos

### ISSUE THREAD

**Issue by zwit5** [kboghdady/youTube_ads_4_pi-hole#4]
after several days of using script I have noticed that videos aren't launching. I commented section for analysing the logs and left downloading blacklists only and rebuild blacklist. Videos started to work fine. So section for analysing the logs needs some readjustments ;-) Nevertheless I appreciate the idea :-)

**Comment by kboghdady** [comment]
Thank you so much zwit5 first for using the script, and also your feedback
I will work on that as well

**Comment by kboghdady** [comment]
I just updated the script. could you please update your script and let me know how it goes
