### ISSUE TITLE
Youtube is also blocked along with ads

### ISSUE THREAD

**Issue by alvaroledesma** [kboghdady/youTube_ads_4_pi-hole#40]
I can't access Youtube along with the ads. I believe DNS is blocking youtube as well as ads

**Comment by kboghdady** [comment]
could you please run ```pihole -t``` while you playing youtube and it is blocked

**Comment by alvaroledesma** [comment]
Yes, I ran it and see all the link being redirected to 0.0.0.0

**Comment by kboghdady** [comment]
I need the logs to see it. my secript doesn't block youtube itself.

**Comment by kboghdady** [comment]
Duplicate of #20

**Comment by kboghdady** [comment]
I am working on it today and updating the list.
if you are using the youtube.sh script make sure to remove both :
rm /etc/pihole/black*
if you are using the gravity list make sure to update it
