### ISSUE TITLE
filtter youtube links from existing local pihole log 

### ISSUE THREAD

**Issue by id4vip** [kboghdady/youTube_ads_4_pi-hole#42]
Hello kboghdady, thanks for your expert guidance. i am running your "youtube.sh" bash command daily.  as you are expert in programming i want to suggest one more thing to add in your bash file. like system check the logs of local pihole data & filter "http: //r3---sn-uxa0n-ttjse.googlevideo. com" like address & in next circle that address also append in your blacklist.txt. 

the overall mean that today from which link i received youtube adds. tomorrow after re-run your program it will detain & closed for future. my overall mean is not to upload our data to your side. but like in our blacklist.txt file. also i am using pihole & unbound combination & in each of my google link"uxa0n" always present. but when i fetch google video data or your file "curl ‘https: //api.hackertarget.com/hostsearch/?q=googlevideo.com" i am not see much these "uxa0n" links. so i am confusing. why this "uxa0n" is coming in my side.   thanks in advance

**Comment by kboghdady** [comment]
Thank you @id4vip for the complment. I had that before, and I will try to make it available again. 
it might take me while to have some time for now during this pandemic, but I will do my best

**Comment by kboghdady** [comment]
@id4vip I just made the update so you can include the domain into the ignore.list and it will be removed.
