### ISSUE TITLE
YouTube Ads still paying but after ads video won't load for me

### ISSUE THREAD

**Issue by RajPatel0929** [kboghdady/youTube_ads_4_pi-hole#46]
Running this on OpenWRT WRT3200ACM

YouTube Ads still paying but after ads video won't load for me

**Comment by kboghdady** [comment]
I removed a lot of DNS that goes into loop please run these commands to update your list
pihole -g ; sudo pihole restartdns

**Comment by ashleycawley** [comment]
> I removed a lot of DNS that goes into loop please run these commands to update your list
> pihole -g ; sudo pihole restartdns

I don't understand this, could you please elaborate?

I'm very familiar with DNS, but less so with pihole.

Looking at other docs I see: `pihole -g`:
_"This will for a download of any updates from the third-party block lists that we source. By default, this command runs once a week via cron, so there’s no need to run it manually unless you want to get some updated lists or you run into a problem with the list."_

Does this mean it is refreshing/updating the lists which are contained within the _Adlist group management_ section of PiHole? If so then how does that help with this issue?

Apologies if I'm misunderstanding its use and thank you for your time and efforts on this project.

**Comment by kboghdady** [comment]
@ashleycawley  if you are using the gravity list not the script you can update the using pihole -g
