### ISSUE TITLE
Ads still playing in browser and app (Android)

### ISSUE THREAD

**Issue by JoshALogs** [kboghdady/youTube_ads_4_pi-hole#47]
Hi, I've recently setup a pi-hole on my network and added your list under "Adlist group management". I updated the gravity list, but YouTube ads are still playing on my Android device through the app and browser. Pi-hole seems to be working fine as it is blocking ads from other sites. Did I add your list correctly?

I'm in the United States, if that helps.

**Comment by kboghdady** [comment]
Hi @JoshALogs  thank you for your input. 
I will check that, and I will get back to you as soon as I can

**Comment by kboghdady** [comment]
Hi @JoshALogs 
could you please make sure that device has the DNS of your pi-hole
