### ISSUE TITLE
does not work with pihole >= 5.0

### ISSUE THREAD

**Issue by hejfelix** [kboghdady/youTube_ads_4_pi-hole#48]
pihole moved to a database store meaning the domains should be inserted to that database instead of writing them to a file.

**Comment by mortensassi** [comment]
@hejfelix do you have a workaround?

**Comment by hejfelix** [comment]
No. It's not that simple. You need to use credentials and a db client so it's vastly different. On the flip side, you need less magical bash wizardry xD

**Comment by mortensassi** [comment]
oh alright thank you for your reply nonetheless! i ended up setting up a cronjob to run a script i found in a post on [reddit](https://www.reddit.com/r/pihole/comments/g9ytt9/youtube_some_success_ymmv_please_test/)

**Comment by kboghdady** [comment]
I just fixed the issue with pihole V5. it is now working with it
