### ISSUE TITLE
Loading until infinity

### ISSUE THREAD

**Issue by SjamonDaal** [kboghdady/youTube_ads_4_pi-hole#49]
My PiHole is blocking the advertisements but when my YouTube player hits the add block within a video it stops playing and starts loading the advertisement until the end of time.

Samsung TV Q60R YouTube Application.

**Comment by kboghdady** [comment]
Thank you @SjamonDaal  I will check that. 
I am sorry I have been very busy the last couple weeks

**Comment by jrow555** [comment]
Running into the same problem over here. 

Happy to provide more info on my specs.

**Comment by kboghdady** [comment]
I removed a lot of DNS that goes into loop please run these commands to update your list 
pihole -g ; sudo pihole restartdns
