### ISSUE TITLE
Is there anyway to add these?

### ISSUE THREAD

**Issue by smokingwheels** [kboghdady/youTube_ads_4_pi-hole#5]
I'm having like these turn up, is there anyway you could add them to your script please ?

p2-galfbu4g6o4ms-recvcqnkwlxh4nur-868998-i1-v6exp3.ds.metric.gstatic.com
p2-galfbu4g6o4ms-recvcqnkwlxh4nur-868998-s1-v6exp3-v4.metric.gstatic.com
p2-galfbu4g6o4ms-recvcqnkwlxh4nur-if-v6exp3-v4.metric.gstatic.com
p2-nfj5wqfccwaig-u32h7kfqb55lkgxx-755042-i1-v6exp3.ds.metric.gstatic.com
p2-nfj5wqfccwaig-u32h7kfqb55lkgxx-755042-i2-v6exp3.v4.metric.gstatic.com
p2-nfj5wqfccwaig-u32h7kfqb55lkgxx-755042-s1-v6exp3-v4.metric.gstatic.com
p4-b26d2myvxmnic-2g7erssxpeljycve-if-v6exp3-v4.metric.gstatic.com
p4-dtpyky5z34ncy-kpslgygro46fb7mf-if-v6exp3-v4.metric.gstatic.com

**Comment by kboghdady** [comment]
are these youtube ads ?
