### ISSUE TITLE
Error running script

### ISSUE THREAD

**Issue by pavelsnajdr** [kboghdady/youTube_ads_4_pi-hole#50]
Hi kboghdady,
thank you for your effort. I have problem with running script, I get this error:

pi@raspberrypi:~/youTube_ads_4_pi-hole $ sudo ./youtube.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  757k  100  757k    0     0  1131k      0 --:--:-- --:--:-- --:--:-- 1131k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  757k  100  757k    0     0  1386k      0 --:--:-- --:--:-- --:--:-- 1389k
sudo: unable to execute /usr/local/bin/pihole: Argument list too long

can you help me what's wrong?
Thank you,
Pavel

**Comment by sroseman** [comment]
Same

**Comment by stewiezc** [comment]
I deleted `sudo` from line 35 in youtube.sh and it works for me now.
https://github.com/kboghdady/youTube_ads_4_pi-hole/blob/master/youtube.sh#L35

**Comment by keerthiteja** [comment]
Same here

**Comment by alia28** [comment]
Try this https://github.com/kboghdady/youTube_ads_4_pi-hole/pull/51
