### ISSUE TITLE
"Database Is Locked"

### ISSUE THREAD

**Issue by Surdified** [kboghdady/youTube_ads_4_pi-hole#52]
Upon running the script manually I am constantly greeted with "Error: database is locked" after it attempts to add any domain to the black list.

The image attached is an example of my issue:

![image](https://user-images.githubusercontent.com/49766393/85930310-31a86e00-b8b3-11ea-9341-918809154b42.png)

**Comment by diamond-shark** [comment]
I got this same error when I was manually running. Turns out I was trying to update while the cronjob was running so that's what the error was.

**Comment by kboghdady** [comment]
yeah just make sure the script isn't running
