### ISSUE TITLE
I don't like the way this is implemented.

### ISSUE THREAD

**Issue by AtomynosAtom** [kboghdady/youTube_ads_4_pi-hole#59]
I do not think so the way you implement the way of importing the domains to pi hole appropriate. Where you import each domain separately. I tried this other way by using pihole5-list-tool. I could easily import a bulk of lists as white lists or as blacklists. I do not understand this approach of yours to import the domains one by one. This is very time consuming and also annoying to disable. Could I know why you take such an approach? Is there any reason?

**Comment by kboghdady** [comment]
I have tried to import it all in one line, but then a lot of users reports they are having issues

**Comment by AtomynosAtom** [comment]
> I have tried to import it all in one line, but then a lot of users reports they are having issues
Did you try using pihole5-list-tool?

**Comment by kboghdady** [comment]
no I didn't

**Comment by kboghdady** [comment]
if you have a suggestion please feel free to add them, and I will review the code and merge it
