### ISSUE TITLE
what is the difference (list vs. script)?

### ISSUE THREAD

**Issue by k-rock** [kboghdady/youTube_ads_4_pi-hole#63]
Hi - what is the difference in adding the block list (https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/youtubelist.txt) to Pi-Hole vs. running this shell script? 

Do they result in the same behavior?

**Comment by T-IOOO** [comment]
I assume no difference at all. I am running pi-hole with the raw list added. Ocasionally running "pihole -g" over SSH

**Comment by TechKat** [comment]
Same thing. Except using just the list, your PiHole will update it every Sunday (default setting).
Using the script, which runs every hour if you follow the instructions, will update the blacklist every hour as described.

YouTube will always be changing their domains to get around blockers. If you went by just the list, you'll probably get the occasional ad here and there. But by script, you're almost guaranteed no ads.

**Comment by kboghdady** [comment]
- The script will work better if you are outside the united states as it collects the domains from your own pihole that you see, and you need to maintain the actual domains in case there is one that blocks your youtube where you need to put the DNS into the ignore.txt file. 
- the list works best in the US and I maintain it to make sure it doesn't block the youtube.
