### ISSUE TITLE
Bed desctiption on README.md 

### ISSUE THREAD

**Issue by ybaidiuk** [kboghdady/youTube_ads_4_pi-hole#64]
Nothing say about changing script youtube.sh !
add lines to desctiptions!

#change  line in script (repoDir) /PATH_TO_REPO/youTube_ads_4_pi-hole/youtube.sh 
 repoDir='/PATH_TO_REPO/youTube_ads_4_pi-hole'

**Comment by kboghdady** [comment]
Thanks @ybaidiuk  for flagging this issue. I should have considered a variety of audiences including beginners.

**Comment by ybaidiuk** [comment]
If you forget put correctly documentation it not mean that I beginner :-)
