### ISSUE TITLE
Script working not as expected.

### ISSUE THREAD

**Issue by ybaidiuk** [kboghdady/youTube_ads_4_pi-hole#65]
I have expected that script will pull and update periodically list of DNS.
What i get:
1. Instead of list each item separate. (for deleting is easier to reinstall pi-hole)
2. black.list and youtube list is just save filese. 
3. Pi-hole can update lists itself. 
4. Bad description.

**Comment by kboghdady** [comment]
It sounds to me you are pretty new for pihole. 
If you read the Readme there are two options : 
1- using the file list where the pihole will update itself.
2- using the script to collect your own Ads from the logs and insert it to the database. 
I am not sure how I can help you with your expectation. 
at the end of the day, it is an open-source project. you are more than welcome to contribute to it.
