### ISSUE TITLE
Do this work on adblock package on openwrt

### ISSUE THREAD

**Issue by freetextmike** [kboghdady/youTube_ads_4_pi-hole#66]
i saw this on the blocklist list and check and it seems not working

**Comment by Laproxi** [comment]
### It's using an OLD format, so the newer versions of PiHole won't accept it.

- [ ] **Currently, an entry looks like this:** 

r5---sn-p5qs7n7z.googlevideo.com

- [X] **However, it should look something like this:**

0.0.0.0 r5---sn-p5qs7n7z.googlevideo.com


@freetextmike

**Comment by residentcode** [comment]
I tested the list block everything 
no video working at all
fresh install

**Comment by kboghdady** [comment]
@residentcode fresh install on pihole ? 
were you using the script or the gravity list?

**Comment by residentcode** [comment]
yes fresh install on pihole but the script doesn't load, I thing pihole doesn't support blacklist.txt  anymore?
so I added the youtubelist.txt and crowed_list.txt as adlists, anyway those lists blocked every video on youtube including ads lol.

**Comment by kboghdady** [comment]
the script takes the list and insert it into the database. no longer using the blacklist.txt

**Comment by residentcode** [comment]
yes but the script doesn't block any video nor any ads  but the adslist block everything this is weird.
I found a trick on the web is when you ad Dot after youtube.com./ all ads disappeared from the video for some reason , can you use this trick somehow for all videos ?

**Comment by kboghdady** [comment]
are you in the US ?
the gravity list is working great for me, and it blocks the ads.

**Comment by residentcode** [comment]
no im in Europe

**Comment by kboghdady** [comment]
gravity works in the US. 
it might be useful to use the script
