### ISSUE TITLE
UNIQUE constraint failed

### ISSUE THREAD

**Issue by TeHashX** [kboghdady/youTube_ads_4_pi-hole#69]
When I run "sudo youtube.sh" I get errors
  [i] Adding r18.sn-a5mlrn7z.googlevideo.com to the blacklist...
Error: UNIQUE constraint failed: domainlist_by_group.domainlist_id, domainlist_by_group.group_id
  [i] Adding r19.sn-a5mlrn7z.googlevideo.com to the blacklist...
Error: UNIQUE constraint failed: domainlist_by_group.domainlist_id, domainlist_by_group.group_id
  [i] Adding r20.sn-a5mlrn7z.googlevideo.com to the blacklist...
Error: UNIQUE constraint failed: domainlist_by_group.domainlist_id, domainlist_by_group.group_id
  [✓] Reloading DNS lists
  [✓] Restarting DNS server

**Comment by kboghdady** [comment]
it is an issue with pihole maybe this will help : https://discourse.pi-hole.net/t/issue-with-gravity-new-internal-blocking-branch/25612
