### ISSUE TITLE
Both steps, or pick one?

### ISSUE THREAD

**Issue by rssw** [kboghdady/youTube_ads_4_pi-hole#72]
Hi, it's not clear if we should be adding the list(s) to the ad lists feature and updating with "pihole -g", or to run the script "youtube.sh" on a schedule witch adds the individual domains to the black.list file.

Are these alternative options to adding domains, or should we do both?

**Comment by burnbabyburn** [comment]
If you add url for youtubelist.txt to your pihole => you'll get the blocklist into your dns
if you use his script with cronjob => You get his blocklist + your personal blocklist (which is generated from you pihole database).

**Comment by kboghdady** [comment]
you can pick one depending on what you prefer 
1- Gravity is maintained by me to make sure that it doesn't block actual videos 
2- the script benefits of blocking videos that come from your region
