### ISSUE TITLE
Incorrect domains

### ISSUE THREAD

**Issue by rssw** [kboghdady/youTube_ads_4_pi-hole#73]
Hi, 

There are a few urls in the blocklist without the ".com", such as:
  r1.sn-p5qs7n7z.a1.googlevideo

I just noticed when I tried removing all the youtube domians from my gravity.db, and these all stayed.

**Comment by burnbabyburn** [comment]
I think thats what he means with this part from README.MD
```
if you experince youtube loops or blocking to the actual video while using the gravity
Please clear the gravity domain list as it some times keep the ignore list :

/usr/bin/sqlite3 /etc/pihole/gravity.db "delete from gravity where domain like '%googlevideo.com%' "
pihole -g
```

**Comment by kboghdady** [comment]
Thank you will delete that shortly
