### ISSUE TITLE
how did you extract this urls 

### ISSUE THREAD

**Issue by DevSaumyadip** [kboghdady/youTube_ads_4_pi-hole#74]
https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/youtubelist.txt

if you please enlight us, how did you manage to get this urs, so that we can also contribute to it and update the list because google throw ads region-specific . and I can update the ads thrown in my region.

**Comment by kboghdady** [comment]
Duplicate of #32
