### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by ab11bkr** [kboghdady/youTube_ads_4_pi-hole#91]
I am trying to uninstall this blacklist so tried the command given:
`/usr/bin/sqlite3 /etc/pihole/gravity.db "delete from domainlist where domain like '%googlevideo.com%' "`
however this returns:
`Error: attempt to write a readonly database`

So then I tried removing all domains from blacklist.txt which was successful, however these domains still show on the blacklist on the pihole admin web interface.

Can someone please help me with this issue as it is giving me problems on YouTube. Thanks

**Comment by xmanwms95** [comment]
@ab11bkr you would need to add `sudo` to the beginning of the command.  Try something like this:
```bash
sudo /usr/bin/sqlite3 /etc/pihole/gravity.db "delete from domainlist where domain like '%googlevideo.com%' "
```

**Comment by ab11bkr** [comment]
Thanks so much. It worked a miracle.

**Comment by CLKRUN** [comment]
`Error: database is locked` after `sudo /usr/bin/sqlite3 /etc/pihole/gravity.db "delete from domainlist where domain like '%googlevideo.com%' "`
