### ISSUE TITLE
how pi-hole will update the lists?

### ISSUE THREAD

**Issue by tomcruces** [kboghdady/youTube_ads_4_pi-hole#98]
I have the Pi-hole lits (black.list, blacklist.txt, etc) in /etc/pihole, so how pi-hole will update the lists?, because with the step to step the "youTube_ads" list are in  "/home/pi/youTube_ads".

**Comment by kboghdady** [comment]
could you please clarify I am not sure I get your question

**Comment by costispavlou** [comment]
I couldnt for the life of me make this work either. 
Apple TV, iPhone, iPad everything plays with ads.
Maybe I'm stupid but I really thought there's no way to block youtube ads via pihole.

**Comment by kboghdady** [comment]
I will work for the a video soon
