### ISSUE TITLE
conflict message in black.list line 9021

### ISSUE THREAD

**Issue by HuiMi24** [kboghdady/youTube_ads_4_pi-hole#99]
conflict message in black.list line 9021

<<<<<<< HEAD
r1---sn-5uaeznr6.googlevideo.com

**Comment by dishather** [comment]
Similar artifacts in youtubelist.txt:

$ diff youtubelist.txt youtubelist_filtered.txt
2161d2160
< <<<<<<< HEAD
2242,2243d2240
< =======
< >>>>>>> d2f35f7df78db44100735cc9bb2b41a5eea3b26c
9224d9220
< >>>>>>> 87d416a3b02885ac656f2890cbe825b1df65fdf0
